### ISSUE TITLE
Strange "localparam integer" behavior

### ISSUE THREAD

**Issue by cliffordwolf** [steveicarus/iverilog#41]
The following module should print '1' (tested with modelsim 10.1d and xsim 2014.2), but iverilog 1572dcd prints '0':

```
module test;
  localparam integer p = -1;
  initial $display("%b", (1 + p) == |0);
endmodule
```

Without the keyword "integer" the module behaves as expected.

**Comment by steveicarus** [comment]
OK, so what do we do about this? Do we just declare it a quirk of the language, or do we put some effort into it?

**Comment by martinwhitaker** [comment]
To fix this, you'd need to change the rules for determining the expression type when elaborating a lossless expression. Doing this would almost certainly introduce other incompatibilities. So I'd just declare this a quirk of Icarus lossless expressions.

Personally, I'd like to make -gstrict-expr-width the default. I think users should have to consciously opt in to non-standard behaviour.

**Comment by cliffordwolf** [comment]
I also think making `-gstrict-expr-width` the default would be a good choice. (Just my two cents.)

**Comment by caryr** [comment]
It is a bit hard to argue with the standard regarding the default behavior even when we think it should be different. It would be nice if it just did the right thing, but I agree with Martin it would likely turn into a large task that may not work as expected anyway since any new rules we come up with are not guaranteed to be internally consistent.

Do we have our first development/V10 difference?

**Comment by cliffordwolf** [comment]
With current git head (dc5429e) this seems to work as expected. :+1: Closing this issue.
